name: Frontend Build and Deploy to GH-Pages

on:
  push:
    branches:
      - main # Запускаем только при пуше в основную ветку
  workflow_dispatch: # Можно запускать вручную

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout 📦️
        uses: actions/checkout@v4

      # Устанавливаем зависимости npm
      - name: Install dependencies ⚙️
        run: |
          npm install --no-audit --no-fund

      # Копируем файлы из src в public (это нужно для сборки)
      - name: Copy assets ✂️
        run: |
          cp -r ./src/* ./public/

      # Публикуем сайт через Actions Deployment
      - name: Publish 🔗
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public # Папка с HTML/CSS/JS
